---
- hosts: lampservers
  tasks:
  - name: 'yum check updates'
    yum: name=* state=latest
  - name: 'install latest apache version'
    yum: pkg=httpd state=latest
  - name: 'install latest mysql'
    yum: pkg=mysql state=latest
  - name: 'install php5'
    yum: pkg=php state=latest
  - name: 'Enable and restart Apache Webserver' 
    service: name=httpd state=restarted enabled=yes
# Firewall Rules
  - name: Flush currest firewall rules
    command: /sbin/iptables -F
  - name: ALL SSH on port 22
    command: /sbin/iptables -I INPUT -p tcp --dport 22 -j ACCEPT 
  - name: Allow HTTPS on port 443
    command: /sbin/iptables -I INPUT -p tcp --dport 443 -j ACCEPT
  - name: Save iptables rules  
    command: service iptables save
# Restart firewall
  - name: Enable and restart firewall rules
    service: name=iptables state=restarted enabled=yes
  - name: Show effect firewall rules
    command: /sbin/iptables -L --line-numbers -n

